---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.buildtools
  - name: robertdebock.ca
  - name: robertdebock.epel
  - name: robertdebock.openssl
  - name: robertdebock.python_pip
  - name: robertdebock.reboot
  - name: robertdebock.update
