---

- name: ensure /etc/openvpn/client exists
  file:
    path: /etc/openvpn/client
    state: directory
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0750"

- name: place client.conf
  template:
    src: client.conf.j2
    dest: "{{ openvpn_client_configuration }}"
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0640"
  notify:
    - restart openvpn
