---
# tasks file for openvpn

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install openvpn packages
  package:
    name: "{{ openvpn_packages }}"
    state: present

- name: setup openvpn server
  include: server.yml
  when:
    - openvpn_role == "server"

- name: setup openvpn client
  include: client.yml
  when:
    - openvpn_role == "client"

- name: start and enable openvpn
  service:
    name: "{{ openvpn_service }}"
    state: started
    enabled: yes
