---
# tasks file for openvpn
- name: include assert.yml
  include_tasks: assert.yml

- name: install openvpn
  package:
    name: "{{ openvpn_packages }}"
    state: present

- block:
    - name: include ca role
      include_role:
        name: robertdebock.ca
      vars:
        ca_openssl_path: "{{ openvpn_certs_directory }}"
        ca_requests:
          - name: server

    - name: generate static encryption key
      command: openvpn --genkey --secret {{ openvpn_static_encryption_key }}
      args:
        creates: "{{ openvpn_static_encryption_key }}"

    - name: save static encryption key
      slurp:
        src: "{{ openvpn_static_encryption_key }}"
      register: openvpn_save_static_encryption_key
  when:
    - openvpn_server is defined
    - openvpn_server | bool

- name: distribute static encryption key
  copy:
    content: "{{ openvpn_save_static_encryption_key.content | b64decode }}"
    dest: "{{ openvpn_static_encryption_key }}"

- block:
    - name: generate dh2048 key
      command: openssl dhparam -out {{ openvpn_dh2048_key }} 2048
      args:
        creates: "{{ openvpn_dh2048_key }}"

    - name: configure openvpn server
      template:
        src: "{{ openvpn_server_config_file }}.j2"
        dest: "{{ openvpn_config_directory }}/{{ openvpn_server_config_file }}"
      notify:
        - restart openvpn
  when:
    - openvpn_server is defined
    - openvpn_server | bool

- name: configure openvpn client
  template:
    src: "{{ openvpn_client_config_file }}.j2"
    dest: "{{ openvpn_config_directory }}/{{ openvpn_client_config_file }}"
  when:
    - openvpn_client is defined
    - openvpn_client | bool

- name: start and enable openvpn server
  service:
    name: "{{ openvpn_service }}"
    state: started
    enabled: yes
  when:
    - openvpn_server is defined
    - openvpn_server | bool
