---
# tasks file for openvpn
- name: test veriables and environment
  assert:
    that:
      - openvpn_package_state is defined
      - openvpn_package_state == "present" or
        openvpn_package_state == "latest" or
        openvpn_package_state == "absent"
      - openvpn_ignore_docker is defined
      - openvpn_ignore_docker or
        not openvpn_ignore_docker

- name: install openvpn
  package:
    name: "{{ openvpn_packages }}"
    state: "{{ openvpn_package_state }}"
  register: openvpn_install_openvpn
  until: openvpn_install_openvpn is succeeded
  retries: 3

- name: generate static encryption key
  command: openvpn --genkey --secret {{ openvpn_static_encryption_key }}
  args:
    creates: "{{ openvpn_static_encryption_key }}"
  when:
    - openvpn_server is defined
    - openvpn_server

- name: save static encryption key
  slurp:
    src: "{{ openvpn_static_encryption_key }}"
  register: openvpn_save_static_encryption_key
  when:
    - openvpn_server is defined
    - openvpn_server

- name: distribute static encryption key
  copy:
    content: "{{ openvpn_save_static_encryption_key.content | b64decode }}"
    dest: "{{ openvpn_static_encryption_key }}"

- name: generate dh2048 key
  command: openssl dhparam -out {{ openvpn_dh2048_key }} 2048
  args:
    creates: "{{ openvpn_dh2048_key }}"
  when:
    - openvpn_server is defined
    - openvpn_server

- name: configure openvpn server
  template:
    src: "{{ openvpn_server_config_file }}.j2"
    dest: "{{ openvpn_config_directory }}/{{ openvpn_server_config_file }}"
  notify:
    - restart openvpn
  when:
    - openvpn_server is defined
    - openvpn_server

- name: configure openvpn client
  template:
    src: "{{ openvpn_client_config_file }}.j2"
    dest: "{{ openvpn_config_directory }}/{{ openvpn_client_config_file }}"
  when:
    - openvpn_client is defined
    - openvpn_client

- name: start and enable openvpn server
  service:
    name: "{{ openvpn_service }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker" or openvpn_ignore_docker
    - openvpn_server is defined
    - openvpn_server
