---

- name: ensure /etc/openvpn/easy-rsa exists
  file:
    path: /etc/openvpn/easy-rsa
    state: directory
    mode: "0755"

- name: easyrsa init-pki
  command: /usr/share/easy-rsa/3/easyrsa init-pki
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki

- name: easyrsa build-ca
  command: /usr/share/easy-rsa/3/easyrsa build-ca nopass
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/ca.crt
  environment:
    EASYRSA_BATCH: "yes"

- name: easyrsa gen-dh
  command: /usr/share/easy-rsa/3//easyrsa gen-dh
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/dh.pem

- name: easyrsa build-server-full server nopass
  command: /usr/share/easy-rsa/3/easyrsa build-server-full server nopass
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/issued/server.crt

- name: easyrsa build-client-full client nopass
  command: /usr/share/easy-rsa/3/easyrsa build-client-full client nopass
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/issued/client.crt

- name: easyrsa gen-crl
  command: /usr/share/easy-rsa/3/easyrsa gen-crl
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/crl.pem

- name: openvpn --genkey --secret /etc/openvpn/easy-rsa/pki/ta.key
  command: openvpn --genkey --secret /etc/openvpn/easy-rsa/pki/ta.key
  args:
    creates: /etc/openvpn/easy-rsa/pki/ta.key

- name: copy files to /etc/openvpn/server
  copy:
    src: /etc/openvpn/easy-rsa/pki/{{ item }}
    dest: /etc/openvpn/server/{{ item | basename }}
    mode: "0640"
    remote_src: yes
  loop:
    - ca.crt
    - dh.pem
    - ta.key
    - issued/client.crt
    - issued/server.crt
    - private/ca.key
    - private/client.key
    - private/server.key

- name: place server.conf
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server/server.conf
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0640"
  notify:
    - restart openvpn
